version: "3.8"

services:
  php:
    image: php:8.2-apache
    container_name: php-mysql-app
    volumes:
      - ../src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: php-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bootcamp
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
